version: '3.7'

services:
  tenant-db:
    container_name: tenant-ms-db
    image: bitnami/postgresql:latest
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: tenant-db
    volumes:
      - tenant_ms_pg_data:/bitnami/postgresql

volumes:
  tenant_ms_pg_data:
